"""Add titel in history

Revision ID: 239462272eb8
Revises: 75145378685b
Create Date: 2023-03-21 21:58:04.147446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '239462272eb8'
down_revision = '75145378685b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_history', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
