"""Add Category table and update relationships

Revision ID: 60afa00d4080
Revises: 676c1ce9535a
Create Date: 2023-03-27 09:27:55.183871

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision = '60afa00d4080'
down_revision = '676c1ce9535a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Creating category table
    op.create_table(
        'category',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('name', sa.String(100), nullable=False, unique=True),
    )

    # Adding new columns to password and password_history
    with op.batch_alter_table('password', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer, sa.ForeignKey('category.id', name='fk_password_category_id')))

    with op.batch_alter_table('password_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer, sa.ForeignKey('category.id', name='fk_password_history_category_id')))


    # Creating the default 'Personal' category
    conn = op.get_bind()
    conn.execute(text("INSERT INTO category (name) VALUES ('Personal')"))

    # Updating existing records to point to the new 'Personal' category
    conn.execute(text("UPDATE password SET category_id = (SELECT id FROM category WHERE name='Personal')"))
    conn.execute(text("UPDATE password_history SET category_id = (SELECT id FROM category WHERE name='Personal')"))

    # Removing the old 'category' columns
    with op.batch_alter_table('password', schema=None) as batch_op:
        batch_op.drop_column('category')

    with op.batch_alter_table('password_history', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint('fk_password_history_category_id', type_='foreignkey')
        batch_op.drop_column('category_id')

    with op.batch_alter_table('password', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=100), server_default=sa.text("'Personal'"), nullable=False))
        batch_op.drop_constraint('fk_password_category_id', type_='foreignkey')
        batch_op.drop_column('category_id')

    op.drop_table('category')
    # ### end Alembic commands ###