"""Add Category table and update relationships

Revision ID: 676c1ce9535a
Revises: 239462272eb8
Create Date: 2023-03-22 17:25:31.039770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '676c1ce9535a'
down_revision = '239462272eb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
