"""Create password_history table2

Revision ID: 75145378685b
Revises: ae015fcdcee1
Create Date: 2023-03-21 21:21:38.777954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75145378685b'
down_revision = 'ae015fcdcee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('password_history')
    op.drop_table('password')
    # ### end Alembic commands ###
