"""Add password_history table

Revision ID: d97af9d65928
Revises: 2a3cf1c9b84e
Create Date: 2023-03-20 23:22:36.576661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd97af9d65928'
down_revision = '2a3cf1c9b84e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('password_history')
    # ### end Alembic commands ###
