name: CI

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest tests/

    - name: Setup environment variables
      run: |
        echo "FERNET_KEY=$(python -c 'from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())')" >> $GITHUB_ENV
        echo "FLASK_APP=main.py" >> $GITHUB_ENV
        echo "FLASK_ENV=development" >> $GITHUB_ENV

    - name: Create database
      run: |
        flask db upgrade

    - name: Insert test data
      run: |
        python test_data.py
