name: CI

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m venv env
        source env/bin/activate
        pip install --upgrade pip
        pip install -r backend/app/requirements.txt
        pip install Flask
        which flask

    - name: Set PYTHONPATH
      run: |
        echo "PYTHONPATH=$(pwd)/backend" >> $GITHUB_ENV

    - name: Setup environment variables
      run: |
        echo "FERNET_KEY=$(python -c 'from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())')" >> $GITHUB_ENV
        echo "FLASK_APP=backend/app/main.py" >> $GITHUB_ENV
        echo "FLASK_DEBUG=1" >> $GITHUB_ENV


    - name: Debug environment
      run: |
        env
        echo $PATH
        echo $VIRTUAL_ENV
        ls -la env/bin
        source env/bin/activate
        which flask
        which python

    - name: Create database
      run: |
        source env/bin/activate
        export FERNET_KEY=${{ env.FERNET_KEY }}
        export FLASK_APP=${{ env.FLASK_APP }}
        export FLASK_ENV=${{ env.FLASK_ENV }}
        flask db init
        flask db upgrade
        python backend/app/create_db.py

    - name: Run tests
      run: |
        source env/bin/activate
        python -m unittest tests.py

    # - name: Run tests
    #   run: |
    #     source env/bin/activate
    #     export FERNET_KEY=${{ env.FERNET_KEY }}
    #     env/bin/pytest backend/tests/

    # - name: Insert test data
    #   run: |
    #     python backend/test_data.py
