name: CI

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m venv env
        source env/bin/activate
        pip install -r requirements.txt

    - name: Set PYTHONPATH
      run: |
        echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

    - name: Setup environment variables
      run: |
        echo "FERNET_KEY=$(python -c 'from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())')" >> $GITHUB_ENV
        echo "FLASK_APP=main.py" >> $GITHUB_ENV
        echo "FLASK_ENV=development" >> $GITHUB_ENV

  - name: Create database
      run: |
        source env/bin/activate
        export FERNET_KEY=${{ env.FERNET_KEY }}
        export FLASK_APP=${{ env.FLASK_APP }}
        export FLASK_ENV=${{ env.FLASK_ENV }}
        env/bin/flask db upgrade

    - name: Run tests
      run: env/bin/pytest backend/tests/

    - name: Insert test data
      run: |
        python backend/test_data.py
